services:
  - type: web
    name: demo-qabot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: OPENAI_API_KEY
        sync: false
      - key: RENDER_GIT_COMMIT
        value: ${RENDER_GIT_COMMIT}   # Auto-set by Render
    healthCheckPath: /api/health

